### PR TITLE
Dynamically adjust climate entity to stove mode when having a hybrid stove

### PR DESCRIPTION
**Pull request by vincentwolsink**
The climate entity now dynamically adjusts to the mode of the stove, and displays the current mode by using a preset. Please let me know what you think (and if it works correctly) @jipem01

### CODE REVIEW

**Comment by jipem01** [comment]
I reviewed the code and it should work, and yes it will be good to have the climate entity switching from one mode to other automatically.
I'll try to test it soon.

But I see interest for keeping numbers for power_set and power_wood_set :
-> Automations : I'm using the scheduler to get rid of the poor programmation capacity (only 4 program possible), and also adapt heating in my home depending on presences...
By automation I should be able to define on/off/target temp/fan mode/power for each time frame.
If the climate entity switch from wood to pellet, i could not use it in automation (cause i don't know if i'm setting wood power or pellet power, and in each time frame i need to set both), or I have to add more complex automation to set current power and to set back good power each time the stove change mode dending on current schedule...

But to not add duplicate entities when not needed, maybe we should create this two entities only when we detect an hybrid stove.

**Comment by vincentwolsink** [comment]
Now keeping the separate power controls in case of a hybrid stove.

**Comment by jipem01** [comment]
It seams to work but need improvements :
- in climate card in lovelace, i have the status displayed as off - wood.

- in entity display i have theses informations : 
    - mode : heating
    - preset : wood
    - fan mode : wood 2 (current power).
  So wood power become fan mode. I don't know if it's expected

**Comment by vincentwolsink** [comment]
The entity display is exactly how it should be. The fan should switch between pellet and wood power and the preset mode should display the current fuel.

can you make a screenshot of the climate card?

**Comment by jipem01** [comment]
Good!
Here is the screenshot : 
Screenshot_20231111-203228_Home Assistant

And associated diag file
[config_entry-aguaiot-8e52fb5148a6b6bd4aba66b72c2ae9aa.json-5.txt](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/13326593/config_entry-aguaiot-8e52fb5148a6b6bd4aba66b72c2ae9aa.json-5.txt)

**Comment by vincentwolsink** [comment]
The climate card also looks good to me? I don’t know what “étient” exactly means. But it looks like it is heating on wood?

Using a preset mode for the fuel might be a bit odd. But unfortunately for stove mode HA only supports a built-in list which doesn’t support our usecase.

**Comment by jipem01** [comment]
"Eteint" means off.
-------- Message d'origine --------De : Vincent Wolsink ***@***.***> Date : 12/11/2023  10:03  (GMT+01:00) À : vincentwolsink/home_assistant_micronova_agua_iot ***@***.***> Cc : jipem01 ***@***.***>, Mention ***@***.***> Objet : Re: [vincentwolsink/home_assistant_micronova_agua_iot] Dynamically adjust climate entity to stove mode when having a hybrid stove (PR #97) 
The climate card also looks good to me? I don’t know what “étient” exactly means. But it looks like it is heating on wood?
Using a preset mode for the fuel might be a bit odd. But unfortunately for stove mode HA only supports a built-in list which doesn’t support our usecase.

**Comment by vincentwolsink** [comment]
Fixed hvac_action (stove status) in #99

**Pull request merged**
